# Generated by Django 4.2.9 on 2024-03-23 16:23

from django.db import migrations
import petstagram.accounts.managers


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='petstagramuser',
            managers=[
                ('objects', petstagram.accounts.managers.PetstagramUserManager()),
            ],
        ),
    ]
